CREATE TABLE Cep (codcep varchar(9) NOT NULL, codmun int4 NOT NULL, CONSTRAINT cep_pkey PRIMARY KEY (codcep));
COMMENT ON TABLE Cep IS 'Cadastro de CEPs dos Munícipios.';
COMMENT ON COLUMN Cep.codcep IS 'Código do CEP';
CREATE TABLE Cliente (codcli SERIAL NOT NULL, cpfcnpjcli varchar(14) NOT NULL UNIQUE, nomcli varchar(100) NOT NULL, CONSTRAINT cliente_pkey PRIMARY KEY (codcli));
COMMENT ON TABLE Cliente IS 'Cadastro de clientes';
COMMENT ON COLUMN Cliente.codcli IS 'Código do cliente';
COMMENT ON COLUMN Cliente.cpfcnpjcli IS 'CPF/CNPJ do cliente';
COMMENT ON COLUMN Cliente.nomcli IS 'Nome do cliente';
CREATE TABLE "Compra Equipamento" (idcom SERIAL NOT NULL, datcomequ timestamp DEFAULT current_timestamp NOT NULL, valcomequ numeric(10, 2) NOT NULL, codfor int4 NOT NULL, codfun int4 NOT NULL, codequ int4 NOT NULL, codtip int4 NOT NULL, CONSTRAINT compra_equipamento_pkey PRIMARY KEY (idcom));
COMMENT ON TABLE "Compra Equipamento" IS 'Compra de equipamentos';
COMMENT ON COLUMN "Compra Equipamento".idcom IS 'ID da compra do equipamento';
COMMENT ON COLUMN "Compra Equipamento".datcomequ IS 'Data da compra do equipamento';
COMMENT ON COLUMN "Compra Equipamento".valcomequ IS 'Valor da compra do equipamento';
CREATE TABLE "Compra Peca" (idcom SERIAL NOT NULL, datcompec timestamp DEFAULT current_timestamp NOT NULL, valcompec numeric(10, 2) NOT NULL, codfor int4 NOT NULL, codfun int4 NOT NULL, codpec int4 NOT NULL, codtip int4 NOT NULL, CONSTRAINT compra_peca_pkey PRIMARY KEY (idcom));
COMMENT ON TABLE "Compra Peca" IS 'Compra de Peças';
COMMENT ON COLUMN "Compra Peca".idcom IS 'ID da compra da peça';
COMMENT ON COLUMN "Compra Peca".datcompec IS 'Data da compra da peça';
COMMENT ON COLUMN "Compra Peca".valcompec IS 'Valor da compra da peça';
CREATE TABLE "Endereco Cliente" (codendcli SERIAL NOT NULL, telcli varchar(20) NOT NULL, emacli varchar(100) NOT NULL UNIQUE, baiendcli varchar(100) NOT NULL, ruaendcli varchar(100) NOT NULL, numendcli varchar(10), comendcli varchar(100), codcep varchar(9) NOT NULL, codtip int4 NOT NULL, codcli int4 NOT NULL, CONSTRAINT endereco_cliente_pkey PRIMARY KEY (codendcli));
COMMENT ON TABLE "Endereco Cliente" IS 'Cadastro dos Endereços de Clientes';
COMMENT ON COLUMN "Endereco Cliente".codendcli IS 'Código do endereço do cliente';
COMMENT ON COLUMN "Endereco Cliente".telcli IS 'Número de telefone do cliente';
COMMENT ON COLUMN "Endereco Cliente".emacli IS 'Email do cliente';
COMMENT ON COLUMN "Endereco Cliente".baiendcli IS 'Bairro do endereço do cliente';
COMMENT ON COLUMN "Endereco Cliente".ruaendcli IS 'Nome da rua do endereço do cliente';
COMMENT ON COLUMN "Endereco Cliente".numendcli IS 'Número do endereço do cliente';
COMMENT ON COLUMN "Endereco Cliente".comendcli IS 'Complemento do endereço do cliente (ponto de referencia)';
CREATE TABLE "Endereco Fornecedor" (codendfor SERIAL NOT NULL, telfor varchar(20) NOT NULL, emafor varchar(100) NOT NULL UNIQUE, baiendfor varchar(100) NOT NULL, ruaendfor varchar(100) NOT NULL, numendfor varchar(10), comendfor varchar(100), codcep varchar(9) NOT NULL, codtip int4 NOT NULL, codfor int4 NOT NULL, CONSTRAINT endereco_fornecedor_pkey PRIMARY KEY (codendfor));
COMMENT ON TABLE "Endereco Fornecedor" IS 'Cadastro dos Endereços de Fornecedores';
COMMENT ON COLUMN "Endereco Fornecedor".codendfor IS 'Código do endereço do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".telfor IS 'Número de telefone do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".emafor IS 'Email do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".baiendfor IS 'Bairro do endereço do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".ruaendfor IS 'Nome da rua do endereço do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".numendfor IS 'Número do endereço do fornecedor';
COMMENT ON COLUMN "Endereco Fornecedor".comendfor IS 'Complemento do endereço do fornecedor (ponto de referencia)';
CREATE TABLE Equipamento (codequ SERIAL NOT NULL, tipequ varchar(80), marequ varchar(100) NOT NULL, modequ varchar(100) NOT NULL, anofabequ int4 NOT NULL, conequ varchar(50) NOT NULL, desequ text, CONSTRAINT equipamento_pkey PRIMARY KEY (codequ));
COMMENT ON TABLE Equipamento IS 'Cadastro dos equipamentos a venda';
COMMENT ON COLUMN Equipamento.codequ IS 'Código do equipamento';
COMMENT ON COLUMN Equipamento.tipequ IS 'Tipo do equipamento';
COMMENT ON COLUMN Equipamento.marequ IS 'Marca do equipamento';
COMMENT ON COLUMN Equipamento.modequ IS 'Modelo do equipamento';
COMMENT ON COLUMN Equipamento.anofabequ IS 'Ano de fabricação do modelo';
COMMENT ON COLUMN Equipamento.conequ IS 'Estado de conservação do equipamento';
COMMENT ON COLUMN Equipamento.desequ IS 'Descrição do equipamento';
CREATE TABLE Estado (codest SERIAL NOT NULL, sigest varchar(2) NOT NULL UNIQUE, nomest varchar(50) NOT NULL, CONSTRAINT estado_pkey PRIMARY KEY (codest));
COMMENT ON TABLE Estado IS 'Cadastro de Unidades Federativas.';
COMMENT ON COLUMN Estado.codest IS 'Código do estado';
COMMENT ON COLUMN Estado.sigest IS 'Sigla do estado';
COMMENT ON COLUMN Estado.nomest IS 'Nome do estado';
CREATE TABLE Fornecedor (codfor SERIAL NOT NULL, cpfcnpjfor varchar(14) NOT NULL UNIQUE, nomfor varchar(100) NOT NULL, codtipfor int4 NOT NULL, CONSTRAINT fornecedor_pkey PRIMARY KEY (codfor));
COMMENT ON TABLE Fornecedor IS 'Cadastro de fornecedores';
COMMENT ON COLUMN Fornecedor.codfor IS 'Código do fornecedor';
COMMENT ON COLUMN Fornecedor.cpfcnpjfor IS 'CPF/CNPJ do fornecedor';
COMMENT ON COLUMN Fornecedor.nomfor IS 'Nome do fornecedor';
CREATE TABLE Funcionario (codfun SERIAL NOT NULL, nomfun varchar(100), cpffun varchar(11) NOT NULL UNIQUE, datnasfun date NOT NULL, CONSTRAINT funcionario_pkey PRIMARY KEY (codfun));
COMMENT ON TABLE Funcionario IS 'Cadastro de funcionarios';
COMMENT ON COLUMN Funcionario.codfun IS 'Código do funcionario';
COMMENT ON COLUMN Funcionario.cpffun IS 'CPF do funcionário';
COMMENT ON COLUMN Funcionario.datnasfun IS 'Data de nascimento do funcionário';
CREATE TABLE Manutencao (idman SERIAL NOT NULL, datman timestamp DEFAULT current_timestamp NOT NULL, desman text, cusman numeric(10, 2) NOT NULL, codfun int4 NOT NULL, codequ int4 NOT NULL, CONSTRAINT manutencao_pkey PRIMARY KEY (idman));
COMMENT ON TABLE Manutencao IS 'Cadastro das manutenções';
COMMENT ON COLUMN Manutencao.idman IS 'ID da manutenção';
COMMENT ON COLUMN Manutencao.datman IS 'Data da manutenção';
COMMENT ON COLUMN Manutencao.desman IS 'Descrição da manutenção';
COMMENT ON COLUMN Manutencao.cusman IS 'Custo da manutenção';
CREATE TABLE Manutencao_Peca (idman int4 NOT NULL, codpec int4 NOT NULL, quapecusa int4 NOT NULL, PRIMARY KEY (idman, codpec));
COMMENT ON COLUMN Manutencao_Peca.quapecusa IS 'Quantidade de peças usadas';
CREATE TABLE Municipio (codmun SERIAL NOT NULL, nommun varchar(50) NOT NULL, codest int4 NOT NULL, CONSTRAINT municipio_pkey PRIMARY KEY (codmun));
COMMENT ON TABLE Municipio IS 'Cadastro de Municípios.';
COMMENT ON COLUMN Municipio.codmun IS 'Código do município.';
COMMENT ON COLUMN Municipio.nommun IS 'Nome do município';
CREATE TABLE "Nota Fiscal" (numnot int8 NOT NULL, dateminot timestamp DEFAULT current_timestamp NOT NULL, CONSTRAINT nota_fiscal_pkey PRIMARY KEY (numnot));
COMMENT ON TABLE "Nota Fiscal" IS 'Registro de notas fiscais';
COMMENT ON COLUMN "Nota Fiscal".dateminot IS 'Data e hora da emição da nota fiscal';
CREATE TABLE Peca (codpec SERIAL NOT NULL, nompec varchar(25) NOT NULL, decpec text, quapecest int4 NOT NULL, valunipec numeric(10, 2) NOT NULL, CONSTRAINT peca_pkey PRIMARY KEY (codpec));
COMMENT ON TABLE Peca IS 'Cadastro de peças';
COMMENT ON COLUMN Peca.codpec IS 'Código da peça';
COMMENT ON COLUMN Peca.nompec IS 'Nome da peça';
COMMENT ON COLUMN Peca.decpec IS 'Descrição da peça';
COMMENT ON COLUMN Peca.quapecest IS 'Quantidade de peca estado';
COMMENT ON COLUMN Peca.valunipec IS 'Valor unitario da peça';
CREATE TABLE "Tipo Compra" (codtip SERIAL NOT NULL, destipcom varchar(25) NOT NULL, CONSTRAINT tipo_compra_pkey PRIMARY KEY (codtip));
COMMENT ON TABLE "Tipo Compra" IS 'Castro do tipo da compra';
COMMENT ON COLUMN "Tipo Compra".codtip IS 'Código do tipo da compra';
COMMENT ON COLUMN "Tipo Compra".destipcom IS 'Descrição do tipo da compra';
CREATE TABLE "Tipo Endereco" (codtip SERIAL NOT NULL, destipend varchar(25) NOT NULL, CONSTRAINT tipo_endereco_pkey PRIMARY KEY (codtip));
COMMENT ON TABLE "Tipo Endereco" IS 'Cadastro de Tipos de Endereço.';
COMMENT ON COLUMN "Tipo Endereco".codtip IS 'Código do tipo de endereço';
COMMENT ON COLUMN "Tipo Endereco".destipend IS 'Descrição do tipo de endereço';
CREATE TABLE "Tipo Fornecedor" (codtipfor SERIAL NOT NULL, destipfor varchar(25) NOT NULL, CONSTRAINT tipo_fornecedores_pkey PRIMARY KEY (codtipfor));
COMMENT ON TABLE "Tipo Fornecedor" IS 'Cadastro do tipo de fornecedores';
COMMENT ON COLUMN "Tipo Fornecedor".codtipfor IS 'Código do tipo do fornecedo';
COMMENT ON COLUMN "Tipo Fornecedor".destipfor IS 'Descrição do tipo do fornecedor';
CREATE TABLE "Tipo venda" (codtipven SERIAL NOT NULL, destipven varchar(25) NOT NULL, CONSTRAINT tipo_venda PRIMARY KEY (codtipven));
COMMENT ON TABLE "Tipo venda" IS 'Cadastro do tipo de venda';
COMMENT ON COLUMN "Tipo venda".codtipven IS 'Código do tipo da venda';
CREATE TABLE "Venda Equipamento" (idven SERIAL NOT NULL, datven timestamp DEFAULT current_timestamp NOT NULL, valven numeric(10, 2) NOT NULL, codcli int4 NOT NULL, codfun int4 NOT NULL, codequ int4 NOT NULL, codtipven int4 NOT NULL, numnot int8 NOT NULL, CONSTRAINT venda_equipamento_pkey PRIMARY KEY (idven));
COMMENT ON TABLE "Venda Equipamento" IS 'Venda de equipamentos';
COMMENT ON COLUMN "Venda Equipamento".idven IS 'ID da venda do equipamento';
COMMENT ON COLUMN "Venda Equipamento".datven IS 'Data da venda do equipamento';
COMMENT ON COLUMN "Venda Equipamento".valven IS 'Valor da venda do equipamento';
CREATE TABLE "Venda peca" (idven SERIAL NOT NULL, datven timestamp DEFAULT current_timestamp NOT NULL, valven numeric(10, 2) NOT NULL, codcli int4 NOT NULL, codfun int4 NOT NULL, codpec int4 NOT NULL, codtipven int4 NOT NULL, numnot int8 NOT NULL, CONSTRAINT venda_peca_pkey PRIMARY KEY (idven));
COMMENT ON TABLE "Venda peca" IS 'Venda de peças';
COMMENT ON COLUMN "Venda peca".idven IS 'ID da venda da peça';
COMMENT ON COLUMN "Venda peca".datven IS 'Data da venda da peça';
COMMENT ON COLUMN "Venda peca".valven IS 'Valor da venda da peça';
ALTER TABLE "Venda peca" ADD CONSTRAINT "FKVenda peca599499" FOREIGN KEY (numnot) REFERENCES "Nota Fiscal" (numnot);
ALTER TABLE "Venda Equipamento" ADD CONSTRAINT "FKVenda Equi520768" FOREIGN KEY (numnot) REFERENCES "Nota Fiscal" (numnot);
ALTER TABLE Fornecedor ADD CONSTRAINT FKFornecedor419882 FOREIGN KEY (codtipfor) REFERENCES "Tipo Fornecedor" (codtipfor);
ALTER TABLE "Venda Equipamento" ADD CONSTRAINT "FKVenda Equi23943" FOREIGN KEY (codtipven) REFERENCES "Tipo venda" (codtipven);
ALTER TABLE "Venda peca" ADD CONSTRAINT "FKVenda peca102674" FOREIGN KEY (codtipven) REFERENCES "Tipo venda" (codtipven);
ALTER TABLE "Venda peca" ADD CONSTRAINT "FKVenda peca596825" FOREIGN KEY (codpec) REFERENCES Peca (codpec);
ALTER TABLE "Venda peca" ADD CONSTRAINT "FKVenda peca819250" FOREIGN KEY (codfun) REFERENCES Funcionario (codfun);
ALTER TABLE "Venda peca" ADD CONSTRAINT "FKVenda peca138444" FOREIGN KEY (codcli) REFERENCES Cliente (codcli);
ALTER TABLE "Venda Equipamento" ADD CONSTRAINT "FKVenda Equi112127" FOREIGN KEY (codequ) REFERENCES Equipamento (codequ);
ALTER TABLE Manutencao_Peca ADD CONSTRAINT FKManutencao991274 FOREIGN KEY (codpec) REFERENCES Peca (codpec);
ALTER TABLE Manutencao_Peca ADD CONSTRAINT FKManutencao698446 FOREIGN KEY (idman) REFERENCES Manutencao (idman);
ALTER TABLE Manutencao ADD CONSTRAINT FKManutencao378470 FOREIGN KEY (codequ) REFERENCES Equipamento (codequ);
ALTER TABLE Manutencao ADD CONSTRAINT FKManutencao964727 FOREIGN KEY (codfun) REFERENCES Funcionario (codfun);
ALTER TABLE "Compra Peca" ADD CONSTRAINT "FKCompra Pec695333" FOREIGN KEY (codtip) REFERENCES "Tipo Compra" (codtip);
ALTER TABLE "Compra Equipamento" ADD CONSTRAINT "FKCompra Equ796292" FOREIGN KEY (codtip) REFERENCES "Tipo Compra" (codtip);
ALTER TABLE "Compra Peca" ADD CONSTRAINT "FKCompra Pec959963" FOREIGN KEY (codpec) REFERENCES Peca (codpec);
ALTER TABLE "Compra Equipamento" ADD CONSTRAINT "FKCompra Equ466890" FOREIGN KEY (codequ) REFERENCES Equipamento (codequ);
ALTER TABLE "Compra Peca" ADD CONSTRAINT "FKCompra Pec262461" FOREIGN KEY (codfun) REFERENCES Funcionario (codfun);
ALTER TABLE "Compra Peca" ADD CONSTRAINT "FKCompra Pec415293" FOREIGN KEY (codfor) REFERENCES Fornecedor (codfor);
ALTER TABLE "Compra Equipamento" ADD CONSTRAINT "FKCompra Equ161502" FOREIGN KEY (codfun) REFERENCES Funcionario (codfun);
ALTER TABLE "Compra Equipamento" ADD CONSTRAINT "FKCompra Equ314334" FOREIGN KEY (codfor) REFERENCES Fornecedor (codfor);
ALTER TABLE "Endereco Cliente" ADD CONSTRAINT "FKEndereco C436627" FOREIGN KEY (codcli) REFERENCES Cliente (codcli);
ALTER TABLE "Endereco Fornecedor" ADD CONSTRAINT "FKEndereco F394403" FOREIGN KEY (codfor) REFERENCES Fornecedor (codfor);
ALTER TABLE "Endereco Cliente" ADD CONSTRAINT "FKEndereco C415682" FOREIGN KEY (codtip) REFERENCES "Tipo Endereco" (codtip);
ALTER TABLE "Endereco Fornecedor" ADD CONSTRAINT "FKEndereco F695178" FOREIGN KEY (codtip) REFERENCES "Tipo Endereco" (codtip);
ALTER TABLE "Endereco Cliente" ADD CONSTRAINT "FKEndereco C739481" FOREIGN KEY (codcep) REFERENCES Cep (codcep);
ALTER TABLE "Endereco Fornecedor" ADD CONSTRAINT "FKEndereco F459985" FOREIGN KEY (codcep) REFERENCES Cep (codcep);
ALTER TABLE Cep ADD CONSTRAINT FKCep906994 FOREIGN KEY (codmun) REFERENCES Municipio (codmun);
ALTER TABLE Municipio ADD CONSTRAINT FKMunicipio180490 FOREIGN KEY (codest) REFERENCES Estado (codest);
ALTER TABLE "Venda Equipamento" ADD CONSTRAINT "FKVenda Equi231071" FOREIGN KEY (codfun) REFERENCES Funcionario (codfun);
ALTER TABLE "Venda Equipamento" ADD CONSTRAINT "FKVenda Equi217175" FOREIGN KEY (codcli) REFERENCES Cliente (codcli);
